if(EXISTS "/mnt/c/Users/joshp/OneDrive/Documents/University/SIT378/SplashKit Core/splashkit-core/projects/cmake/skunit_tests_tests-b12d07c.cmake")
  include("/mnt/c/Users/joshp/OneDrive/Documents/University/SIT378/SplashKit Core/splashkit-core/projects/cmake/skunit_tests_tests-b12d07c.cmake")
else()
  add_test(skunit_tests_NOT_BUILT-b12d07c skunit_tests_NOT_BUILT-b12d07c)
endif()
